landmarks: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]

features:
  # 손목 간격 (T자로 벌린 상태)
  - name: wrist_distance
    type: distance
    points: [15, 16]
  
  # 팔꿈치 각도 (펴진 상태)
  - name: left_elbow_angle
    type: angle
    points: [11, 13, 15]
  - name: right_elbow_angle
    type: angle
    points: [12, 14, 16]

  # 어깨와 손목의 수평
  - name: left_arm_vertical
    type: delta_y
    points: [11, 15]

  - name: right_arm_vertical
    type: delta_y
    points: [12, 16]

  - name: arms_vertical
    type: delta_y
    points: [15, 16]
  
  # 어깨 정렬
  - name: shoulder_alignment
    type: delta_y
    points: [11, 12]

thresholds:
  min_wrist_distance: 0.5
  max_wrist_distance: 1.3

  min_left_elbow_angle: 150
  min_right_elbow_angle: 150

  min_left_arm_vertical: -0.07
  max_left_arm_vertical: 0.07
  min_right_arm_vertical: -0.07
  max_right_arm_vertical: 0.07

  min_arms_vertical: -0.15
  max_arms_vertical: 0.15

  min_shoulder_alignment: -0.06
  max_shoulder_alignment: 0.06


cycles:
  type: calibration
  target_frames: 30