landmarks: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]

features:
  - name: left_elbow_angle
    type: angle
    points: [11, 13, 15]
  - name: right_elbow_angle
    type: angle
    points: [12, 14, 16]

  # Ear–Nose–Ear 법선 기반 pitch proxy
  - name: head_pitch_proxy
    type: normal_vector_pitch
    points: [7, 0, 8]      # (leftEar, nose, rightEar)


thresholds:
  min_left_elbow_angle: 160    # 팔꿈치가 충분히 펴져 있어야 함 (단위: 도)
  min_right_elbow_angle: 160

  # proxy 각도가 10° 이상이면 뒤로 젖힌 것으로 간주
  min_head_pitch_proxy: 10
  
  min_hold_duration_sec: 10    # 자세를 유지해야 하는 최소 시간 (단위: 초)


cycles:
  type: hold      # rep vs hold 구분 플래그
  count: 1        # 10초 유지 동작을 1회 수행해야 성공