landmarks: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]

features:
  - name: left_elbow_angle
    type: angle
    points: [11, 13, 15]
  - name: right_elbow_angle
    type: angle
    points: [12, 14, 16]

  - name: left_hand_alignment
    type: delta_y
    points: [2, 15]   # 왼쪽 눈 - 왼쪽 손목 

  - name: right_hand_alignment
    type: delta_y
    points: [5, 16]

   # 고개 각도 감지를 위한 입-귀 관계
  - name: left_mouth_ear_y_diff
    type: delta_y
    points: [9, 7]  # 
  
  - name: right_mouth_ear_y_diff  
    type: delta_y
    points: [8, 10]  
    


thresholds:
  min_left_elbow_angle:    # 팔꿈치가 충분히 펴져 있어야 함 (단위: 도)
    value: 160
    message: "왼쪽 팔이 구부러졌어요. 팔을 쭉 뻗어주세요."
  min_right_elbow_angle: 
    value: 160
    message: "오른쪽 팔이 구부러졌어요. 팔을 쭉 뻗어주세요."

  min_left_hand_alignment:      # 손이 눈보다 위쪽에 위치하기만 하면 팔을 위로 들었다고 판단
    value: 0.01
    message: "왼쪽 팔을 더 위로 올려야 해요."
  min_right_hand_alignment: 
    value: 0.01     
    message: "오른쪽 팔을 더 위로 올려야 해요."

  max_left_mouth_ear_y_diff: 
    value: 0.02
    message: "고개를 더 젖히거나, 카메라와 너무 멀리 떨어져 있을 수 있어요."
  max_right_mouth_ear_y_diff: 
    value: 0.02
    message: "고개를 더 젖히거나, 카메라와 너무 멀리 떨어져 있을 수 있어요."
  
  min_hold_duration_sec: 10    # 자세를 유지해야 하는 최소 시간 (단위: 초)

  calibration_min_left_mouth_ear_y_diff:
    calibration_key: left_mouth_ear_y_diff
    operator: less_than
    offset: 0.005
    message: "고개를 더 젖히거나, 카메라와 너무 멀리 떨어져 있을 수 있어요."
    
  calibration_min_right_mouth_ear_y_diff:
    calibration_key: right_mouth_ear_y_diff
    operator: less_than
    offset: 0.005
    message: "고개를 더 젖히거나, 카메라와 너무 멀리 떨어져 있을 수 있어요."


cycles:
  type: hold      # rep vs hold 구분 플래그
  count: 1        # 10초 유지 동작을 1회 수행해야 성공

  
calibration:
  - left_eye_ear_y_diff
  - right_eye_ear_y_diff