landmarks: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]

features:
  - name: left_elbow_angle
    type: angle
    points: [11, 13, 15]
  - name: right_elbow_angle  
    type: angle
    points: [12, 14, 16]
  - name: shoulder_alignment
    type: delta_y
    points: [11, 12]

  - name: left_shoulder_hand_alignment
    type: delta_y
    points: [11, 15]   # 왼쪽 어깨 - 왼쪽 손목 

  - name: right_shoulder_hand_alignment
    type: delta_y
    points: [12, 16]   

thresholds:
  max_shoulder_alignment: 0.05 # 수평 유지만 확인
  # 팔꿈치가 충분히 펴져 있어야 함

  min_left_elbow_angle:       # 완전히 펴지지 않아도 허용 (기존 160에서 완화)
    value: 140
    message: "왼쪽 팔이 구부러졌어요. 팔을 쭉 뻗어주세요."
  min_right_elbow_angle:                        
    value: 140
    message: "오른쪽 팔이 구부러졌어요. 팔을 쭉 뻗어주세요."
                                                
  # min_left_shoulder_hand_alignment: -0.1      
  # min_right_shoulder_hand_alignment: -0.1     
  # 팔을 뒤로 젖히는 스트레칭, 카메라 각도 특성상 팔을 쭉 폈음에도 구부러져 보임
  # 또한, 아래로 팔이 내려가 보이는 특징 때문에 음수 판단은 x

  max_left_shoulder_hand_alignment: 
    value: 0.1
    message: "왼쪽 팔이 너무 위로 올라갔어요."
  max_right_shoulder_hand_alignment: 
    value: 0.1     
    message: "왼쪽 팔이 너무 위로 올라갔어요."

  # 자세 유지 시간
  min_hold_duration_sec: 10

cycles:
  type: hold      # 자세 유지형
  count: 1        # 10초 유지 동작을 1회 수행해야 성공

  # z축은 절대 안 됨을 확인함... 포기