landmarks: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]

features:
  # 양손 맞잡은 거리 (손목15 ↔ 손목16)
  - name: hand_clasp_distance
    type: distance
    points: [15, 16]
  
  # 팔을 쭉 뻗었는지 확인 (어깨-팔꿈치-손목 각도)
  - name: left_arm_angle
    type: angle
    points: [11, 13, 15]  # 왼쪽 어깨-팔꿈치-손목
  - name: right_arm_angle
    type: angle
    points: [12, 14, 16]  # 오른쪽 어깨-팔꿈치-손목

      # 손 위치 정의하여 자세가 올바른지 판단, 위로 뻗었는지 확인
  - name: left_hand_y_alignment
    type: delta_y
    points: [2, 15]   # 눈이 손목보다 아래에 있으면 o
  - name: right_hand_y_alignment
    type: delta_y
    points: [5, 16]   # 양수여야 함

  # 눈 레벨 차이 
  - name: eye_level_diff
    type: delta_y
    points: [2, 5] 
  
  # 어깨 레벨 차이 
  - name: shoulder_level_diff
    type: delta_y
    points: [11, 12]  

thresholds:
  # 손을 맞잡은 상태 확인
  max_hand_clasp_distance: 0.5
  
  # 팔을 위로 뻗었는지 확인
  min_left_hand_y_alignment: 
    value: 0
    message: "왼쪽 팔을 위로 드세요."
  min_right_hand_y_alignment: 
    value: 0
    message: "오른쪽 팔을 위로 드세요."


  min_left_arm_angle: 150   # 150도 이상이면 거의 수직
  min_right_arm_angle: 150
  min_hold_duration_sec: 10  # 사용자가 10초 동안 자세를 유지해야 함

cycles:
  type: hold
  count: 1

# 방향 판단 로직
direction:
  left:
    eye_level_diff: 
      sign: positive  # 양수면 왼쪽
      threshold: 0.01  # 최소 레벨 차이
    # shoulder_level_diff:    # 대체로 어깨가 부정확한 양상
    #   sign: positive
    #   threshold: 0.03
  right:
    eye_level_diff:
      sign: negative  # 음수면 오른쪽
      threshold: 0.01
    # shoulder_level_diff:
    #   sign: negative
    #   threshold: 0.03
