landmarks: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]

features:
  - name: left_elbow_angle
    type: angle
    points: [11, 13, 15]
  - name: right_elbow_angle
    type: angle
    points: [12, 14, 16]

  # 손 위치 정의하여 자세가 올바른지 판단
  - name: left_hand_y_alignment
    type: delta_y
    points: [15, 13]   # 손목 - 팔꿈치 > 0 이어야 함.
  - name: right_hand_y_alignment
    type: delta_y
    points: [16, 14]   # 양수여야 함

  - name: left_hand_x_alignment
    type: delta_x
    points: [13, 15]  # 양수여야 함
  - name: right_hand_x_alignment
    type: delta_x
    points: [16, 14]  # 양수여야 함


   # 고개 각도 감지를 위한 눈-귀 관계
  - name: left_eye_ear_y_diff
    type: delta_y
    points: [7, 2]  # 왼쪽 귀 Y - 왼쪽 눈 Y
  
  - name: right_eye_ear_y_diff  
    type: delta_y
    points: [8, 5]  # 오른쪽 귀 Y - 오른쪽 눈 Y


thresholds:
  max_left_elbow_angle: 
    value: 60
    message: "왼쪽 팔이 부정확해요."
  max_right_elbow_angle: 
    value: 60
    message: "오른쪽 팔이 부정확해요."

  min_left_hand_y_alignment:    
    value: 0.01
    message: "왼쪽 팔이 부정확해요."
  min_right_hand_y_alignment: 
    value: 0.01     
    message: "오른쪽 팔이 부정확해요."

  min_left_hand_x_alignment:   
    value: 0.01
    message: "왼쪽 팔이 부정확해요."
  min_right_hand_x_alignment: 
    value: 0.01     
    message: "오른쪽 팔이 부정확해요."

  max_left_mouth_ear_y_diff: 
    value: 0.02
    message: "고개를 더 젖히거나, 카메라와 너무 멀리 떨어져 있을 수 있어요."
  max_right_mouth_ear_y_diff: 
    value: 0.02
    message: "고개를 더 젖히거나, 카메라와 너무 멀리 떨어져 있을 수 있어요."
  
  min_hold_duration_sec: 10    # 자세를 유지해야 하는 최소 시간 (단위: 초)

  calibration_min_left_mouth_ear_y_diff:
    calibration_key: left_mouth_ear_y_diff
    operator: less_than
    offset: 0.005
    message: "고개를 더 젖히거나, 카메라와 너무 멀리 떨어져 있을 수 있어요."
    
  calibration_min_right_mouth_ear_y_diff:
    calibration_key: right_mouth_ear_y_diff
    operator: less_than
    offset: 0.005
    message: "고개를 더 젖히거나, 카메라와 너무 멀리 떨어져 있을 수 있어요."


cycles:
  type: hold      # rep vs hold 구분 플래그
  count: 1        # 10초 유지 동작을 1회 수행해야 성공


calibration:
  - left_mouth_ear_y_diff
  - right_mouth_ear_y_diff