landmarks: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]

features:
  # 팔을 좌우로 벌려 가슴을 펴는 동작: 어깨-팔꿈치-손목 각도
  - name: left_arm_angle
    type: angle
    points: [11, 13, 15]
  - name: right_arm_angle
    type: angle
    points: [12, 14, 16]

  # 팔꿈치의 z축 깊이 측정: 가슴 개방 정도 감지
  - name: left_elbow_z
    type: coordinate_z
    points: [13]
  - name: right_elbow_z
    type: coordinate_z
    points: [14]

  # Ear–Nose–Ear 법선 기반 pitch proxy
  - name: head_pitch_proxy
    type: normal_vector_pitch
    points: [7, 0, 8]      # (leftEar, nose, rightEar)

thresholds:
  min_left_elbow_flexion:   70   # 70° 이상(팔을 충분히 굽힌 상태)
  max_left_elbow_flexion:  110   # 110° 이하(너무 펴지지 않도록)
  min_right_elbow_flexion:  70
  max_right_elbow_flexion: 110

  max_left_elbow_z:    0.10      # 가슴 개방 정도
  max_right_elbow_z:   0.10

  min_head_pitch_proxy: 10       # 뒤로 젖힌 정도 최소 각도

cycles:
  type: rep
  method: peaks
  feature: head_pitch_proxy
  count: 5

  # peaks/troughs 기반 분할을 위한 최소 진폭(°)
  min_swing: 2

  # 각 상태별 최소 유지시간(초)
  min_hold_back_sec:    0.3
  min_hold_forward_sec: 0.3

# 반복요약(aggregate) 설정
aggregate:
  - name: swing_amplitude
    type: amplitude
    target_feature: head_pitch_proxy

  - name: cycle_duration
    type: duration
