landmarks: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]

features:
  # 팔을 좌우로 벌려 가슴을 펴는 동작: 어깨-팔꿈치-손목 각도
  - name: left_arm_angle
    type: angle
    points: [11, 13, 15]
  - name: right_arm_angle
    type: angle
    points: [12, 14, 16]

  # 손이 일정 범위 코보다 아래로 내려가지 않게 함
  - name: left_hand_nose_y_diff
    type: delta_y
    points: [15, 0] # 왼손목 - 코

  - name: right_han_nose_y_diff
    type: delta_y
    points: [16, 0]

  - name: left_eye_ear_y_diff
    type: delta_y
    points: [7, 2]  # 왼쪽 귀 Y - 왼쪽 눈 Y
  
  - name: right_eye_ear_y_diff  
    type: delta_y
    points: [8, 5]  # 오른쪽 귀 Y - 오른쪽 눈 Y

thresholds:
  min_left_elbow_flexion:   70   # 70° 이상(팔을 충분히 굽힌 상태)
  max_left_elbow_flexion:  110   # 110° 이하(너무 펴지지 않도록)
  min_right_elbow_flexion:  70
  max_right_elbow_flexion: 110

  max_left_hand_nose_y_diff:
    value: 0.3
    message: "왼손이 너무 아래로 내려갔어요."
  min_left_hand_nose_y_diff:
    value: -0.1
    message: "손이 너무 위로 올라갔어요."
  max_right_hand_nose_y_diff:
    value: 0.3
    message: "오른손이 너무 아래로 내려갔어요."
  min_right_hand_nose_y_diff:
    value: -0.1
    message: "오른손이 너무 위로 올라갔어요."



cycles:
  type: rep
  method: peaks
  feature: head_pitch_proxy
  count: 5

  # peaks/troughs 기반 분할을 위한 최소 진폭(°)
  min_swing: 2

  # 각 상태별 최소 유지시간(초)
  min_hold_back_sec:    0.3
  min_hold_forward_sec: 0.3

# 반복요약(aggregate) 설정
aggregate:
  - name: swing_amplitude
    type: amplitude
    target_feature: 

  - name: cycle_duration
    type: duration
