landmarks: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]

sides:
  - name: left
    features:
      # 1) 회전 팔의 수직 유지 각도
      - name: left_arm_vertical_angle
        type: angle
        points: [11, 13, 15]
      # 3) 고정 팔이 회전 팔꿈치를 잡고 있는지 확인
      - name: left_hand_hold_elbow_distance
        type: distance
        points: [15, 14]

    thresholds:
      min_left_arm_vertical_angle:       160  
      max_left_hand_hold_elbow_distance:  0.08

    cycles:
      type: rep
      method: peaks
      feature: left_arm_vertical_angle
      count: 3
      min_swing: 18               # 최소 각도 진폭 (°)
      min_hold_back_sec:    0.5   # 접힌 상태 최소 유지 시간
      min_hold_forward_sec: 0.5   # 수직 상태 최소 유지 시간
      min_cycle_duration_sec: 2

    aggregate:
    - name: swing_amplitude
      type: amplitude
      target_feature: left_arm_vertical_angle
    - name: cycle_duration
      type: duration


  - name: right
    features:
      - name: right_arm_vertical_angle
        type: angle
        points: [12, 14, 16]
      - name: right_hand_hold_elbow_distance
        type: distance
        points: [16, 13]

    thresholds:
      min_right_arm_vertical_angle:       160
      max_right_hand_hold_elbow_distance:  0.08

    cycles:
      type: rep
      method: peaks
      feature: right_arm_vertical_angle
      count: 3
      min_swing: 18
      min_hold_back_sec:    0.5
      min_hold_forward_sec: 0.5
      min_cycle_duration_sec: 2

    aggregate:
    - name: swing_amplitude
      type: amplitude
      target_feature: right_arm_vertical_angle
    - name: cycle_duration
      type: duration
