landmarks: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]

sides:
  - name: right
    features:
      # 오른손목(16) ↔ 왼쪽 귀(7)
      - name: right_hand_grab_distance
        type: distance
        points: [16, 7]
      # 왼손은 왼쪽 어깨 뒤로 → 왼손목(15) ↔ 왼쪽 어깨(11)
      - name: left_shoulder_grab_distance
        type: distance
        points: [15, 11]
      # 얼굴 회전 방향(머리 돌림: yaw) 감지: 코(0)–오른쪽 어깨(12)–왼쪽 어깨(11)
      - name: right_head_yaw_angle
        type: angle
        points: [0, 12, 11]

    thresholds:
      max_right_hand_grab_distance:     0.05
      max_left_shoulder_grab_distance: 0.05
      min_right_head_yaw_angle:         20    # baseline 대비 회전 각도
      min_hold_duration_sec:           10

    cycles:
      type: hold
      count: 1
      min_hold_duration_sec: 10

  - name: left
    features:
      # 왼손목(15) ↔ 오른쪽 귀(8)
      - name: left_hand_grab_distance
        type: distance
        points: [15, 8]
      # 오른손은 오른쪽 어깨 뒤로 → 오른손목(16) ↔ 오른쪽 어깨(12)
      - name: right_shoulder_grab_distance
        type: distance
        points: [16, 12]
      # 얼굴 회전 방향 감지: 코(0)–왼쪽 어깨(11)–오른쪽 어깨(12)
      - name: left_head_yaw_angle
        type: angle
        points: [0, 11, 12]

    thresholds:
      max_left_hand_grab_distance:     0.05
      max_right_shoulder_grab_distance: 0.05
      min_left_head_yaw_angle:          20    # baseline 대비 회전 각도
      min_hold_duration_sec:            10

    cycles:
      type: hold
      count: 1
      min_hold_duration_sec: 10
