landmarks: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]

features:
  - name: left_elbow_angle
    type: angle
    points: [11, 13, 15]
  - name: right_elbow_angle
    type: angle
    points: [12, 14, 16]

  # 손 위치 정의하여 자세가 올바른지 판단
  - name: left_Lhand_eye_y_diff  # 왼쪽 방향일 때 왼손
    type: delta_y
    points: [5, 15]   # 왼쪽 눈보다 왼쪽 손목이 위에 있어야 함. 양수여야 함
  - name: left_Lhand_Rhand_y_diff  # 왼쪽 손목이 오른쪽 손목보다 위에 있어야 함. 양수
    type: delta_y
    points: [16, 15]   

  - name: right_Rhand_eye_y_diff   # 양수
    type: delta_y
    points: [2, 16]   
  - name: right_Rhand_Lhand_y_diff   # 양수
    type: delta_y
    points: [15, 16]   

  - name: left_Lhand_x_alignment  # 왼쪽 방향일 때 왼손
    type: delta_x
    points: [15, 0]   # 왼손목 - 코. pos, (-)
  - name: left_Rhand_x_alignment  # 왼쪽 방향 오른손
    type: delta_x
    points: [16, 14]   # 팔꿈치보다 손목을 안으로. 관대하게 설정하는 게 좋을 듯 neg

  - name: right_Lhand_x_alignment
    type: delta_x
    points: [15, 13]    # pos
  - name: right_Rhand_x_alignment
    type: delta_x
    points: [16, 0]    # 오른손목 - 코. neg, (-)


  - name: left_nose_ear_shorter   # 왼쪽귀-코 거리가 짧으면 1,  오른쪽귀-코 거리가 짧으면 0
    type: distance_comparison
    points: [7, 0, 8, 0]


thresholds:

  min_hold_duration_sec: 10    # 자세를 유지해야 하는 최소 시간 (단위: 초)


cycles:
  type: hold
  count: 1

# 방향 판단 로직
direction:
  left:
    left_elbow_angle: 
      sign: negative
      threshold: -100
    right_elbow_angle:
      sign: negative
      threshold: -70

    left_nose_ear_shorter:
      sign: positive
      threshold: 0.9

    left_Lhand_eye_y_diff:
      sign: positive
      threshold: 0.05
    left_Lhand_Rhand_y_diff:
      sign: positive
      threshold: 0.01
    left_Lhand_x_alignment:
      sign: negative
      threshold: -0.1
    left_Rhand_x_alignment:
      sign: positive
      threshold: 0.05

  right:
    left_elbow_angle: 
      sign: negative 
      threshold: -70
    right_elbow_angle:
      sign: negative
      threshold: -100

    left_nose_ear_shorter:
      sign: negative
      threshold: -0.1
      
    right_Rhand_eye_y_diff:
      sign: positive
      threshold: 0.05
    right_Rhand_Lhand_y_diff:
      sign: positive
      threshold: 0.01
    right_Lhand_x_alignment:
      sign: negative
      threshold: 0.05
    right_Rhand_x_alignment:
      sign: positive
      threshold: -0.1